services:
  web:
    build:
      context: .
    working_dir: /app
    command: sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 myproject.asgi:application"
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - TZ=Africa/Harare
    volumes:
      - ./:/app
    depends_on:
      - redis

  worker_loriot:
    build:
      context: .
    working_dir: /app
    command: python manage.py loriot_stream --url ${LORIOT_WS_URL}
    environment:
      - REDIS_HOST=redis
      - LORIOT_WS_URL=${LORIOT_WS_URL}
      - TZ=Africa/Harare
    volumes:
      - ./:/app
    depends_on:
      - redis

  worker_mqtt:
    build:
      context: .
    working_dir: /app
    command: python manage.py mqtt_listen --debug
    environment:
      - REDIS_HOST=redis
      - MQTT_BROKER_HOST=${MQTT_BROKER_HOST}
      - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_TOPIC=${MQTT_TOPIC}
      - TZ=Africa/Harare
    volumes:
      - ./:/app
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  generator:
    build:
      context: .
    working_dir: /app
    command: sh -c "while true; do python manage.py generate_sensor_readings --count 5 --mqtt; sleep 10; done"
    environment:
      - REDIS_HOST=redis
      - TZ=Africa/Harare
    volumes:
      - ./:/app
    depends_on:
      - web